name: Update Scholar Metrics

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight UTC
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

  - name: Fetch Google Scholar metrics
        run: Rscript scripts/update_scholar_metrics.R

      - name: Debug output
        run: |
          ls -al scholar-metrics.json
          cat scholar-metrics.json

      - name: Commit & push updated metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "chore: update Google Scholar metrics"
          file_pattern: "scholar-metrics.json"
          
