name: Update Scholar Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch Google Scholar metrics
        run: python scripts/update_scholar_metrics.py

      - name: Debug ls
        run: |
          ls -al .
          cat scholar-metrics.json || echo "scholar-metrics.json not found"

      - name: Commit and push updated metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "chore: update Google Scholar metrics"
          file_pattern: "scholar-metrics.json"
